server:
  port: 8080

spring:
  application:
    name: rbac-demo

  datasource:
    url: jdbc:postgresql://localhost:5432/rbac_demo
    username: postgres
    password: postgres
    # password: rauliqbal1324
    
    hikari:
      minimum-idle: 5
      maximum-idle: 50
      idle-timeout: 30000 

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
